blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("",views.index,name="BlogHome"),
    path("blogpost/<int:id>",views.blogpost,name="blogPost"),
    path("createpost",views.createpost,name="createpost"),
]

mac/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("",views.index,name="Home"),
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('blog/',include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blogpost(models.Model):
    post_id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=50)
    head0=models.CharField(max_length=50,default="")
    chead0=models.CharField(max_length=5000,default="")
    head1=models.CharField(max_length=50,default="")
    chead1=models.CharField(max_length=5000,default="")
    head2=models.CharField(max_length=50,default="")
    chead2=models.CharField(max_length=5000,default="")
    pub_date=models.DateField()
    thumbnail=models.ImageField(upload_to="shop/images",default="")


    def __str__(self):
        return self.title

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
import json
from .models import Blogpost
from datetime import date



def index(request):
    myposts = Blogpost.objects.all()
    return render(request,"blog/index.html",
                  {'myposts':myposts})
def blogpost(request,id):
    post=Blogpost.objects.filter(post_id=id)[0]
    return render(request,"blog/blogpost.html",{'post':post})

def createpost(request):
    print("Yahaan Tak To Aa Raha Hai")
    if request.method=="POST":
        print("HO GYA")    
        title=    request.POST.get('title','')
        head0=    request.POST.get('head0','')
        chead0=   request.POST.get('chead0','')
        head1=    request.POST.get('head1','')
        chead1=   request.POST.get('chead1','')
        thumbnail=request.POST.get('thumbnail','')
        # post = Blogpost(request.POST,request.FILES)
        post = Blogpost(title=title,head0=head0,chead0=chead0,head1=head1,chead1=chead1,pub_date=date.today(),thumbnail=thumbnail)
        print(thumbnail)
        post.save()
        print("Saved")
    return render(request,"blog/createpost.html")
    
    

blog/templates/blog/basic.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="icon"
    href="https://static-assets-web.flixcart.com/batman-returns/batman-returns/p/images/logo_lite-cbb357.png"
    type="image/png">
  <title>{% block title %}My Awesome Cart {% endblock %}</title>
  <style>
    {% block css %}
      {% endblock %}
  </style>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v19.0"
    nonce="U1s3RMCl"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/shop">My Awesome Cart</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/shop">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/shop/aboutus">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/shop/tracker">Tracker</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/shop/contactus">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/blog">Blog</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" method="GET">
        <input class="form-control mr-sm-2" name="product" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <a>
        <button type="button" class="btn btn-secondary mx-2" id="popcart" data-bs-container="body" data-toggle="popover"
          data-placement="bottom" data-html="true" data-content="Bottom popover">
          Cart(<span id="cart">0</span>)
        </button>
      </a>
    </div>
  </nav>
  {% block body %} {% endblock %}
  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
    integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
    integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
    crossorigin="anonymous"></script>

  {% block js %}
  {% endblock %}
</body>

</html>

blog/templates/blog/createpost.html
{% extends 'shop/basic.html' %}
{% block css %}

<!-- body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f2f2f2;
} -->

.iconcontainer{
max-width: 600px;
display: flex;
margin: 20px auto;
}

.icon{
width:100px;
height:100px;
display:flex;
align-items:center;
margin:auto auto auto 50px;
}

.formcontainer {
max-width: 600px;
margin: 30px auto;
padding: 20px;
background-color: #343a40;
border-radius: 8px;
box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.formcontainer h2 {
text-align: center;
color: #018749;
}

.formcontainer form-group {
margin-bottom: 20px;
}

.formcontainer label {
display: block;
margin-bottom: 5px;
font-weight: bold;
color: #555;
}

.formcontainer input[type="text"],
.formcontainer input[type="email"],
.formcontainer input[type="tel"],
.formcontainer textarea {
width: 100%;
padding: 10px;
border: 1px solid #ccc;
border-radius: 5px;
box-sizing: border-box;
}

.formcontainer textarea {
resize: vertical;
}

.formcontainer button {
display: block;
width: 100%;
padding: 10px;
background-color: #007bff;
color: #fff;
border: none;
border-radius: 5px;
cursor: pointer;
font-size: 16px;
transition: background-color 0.3s ease;
}

.fomrcontainer button:hover {
background-color: #0056b3;
}

.socialicons{
margin-top:20%;
}
{% endblock %}
{% block body %}

<div class="formcontainer">
    <div class="container">
        <h2>Have Something? Share!</h2>
        <form action="/blog/createpost" method="post" > {% csrf_token %}
            <div class="form-group">
                <input placeholder="What's it about?" type="text" id="title" name="title" autocomplete="on" required>
            </div>
            <div class="form-group">
                <input placeholder="Heading Goes Here" type="text" id="head0" name="head0" autocomplete="on" required>
            </div>
            <div class="form-group">
                <textarea placeholder="Please Share your thoughts" id="chead0" name="chead0" rows="4" autocomplete="on"
                    required></textarea>
            </div>
            <div class="form-group">
                <input placeholder="Having Something related?" type="text" id="head1" name="head1" autocomplete="on" required>
            </div>
            <div class="form-group">
                <textarea placeholder="Don't hesitate to write." id="chead1" name="chead1" rows="4" autocomplete="on"
                    required></textarea>
            </div>
            <div>
                <input type="date" name="date" id="date">
            </div>
            <div class="flex-container">
                <label class="required" for="id_thumbnail">Thumbnail:</label>
                    <input type="file" name="thumbnail" accept="image/*" required="" id="id_thumbnail">
        </div>
            <button type="submit">Submit</button>
        </form>
    </div>
</div>
<div class="iconcontainer">
    <div class="icon fb">
        <a href="https://www.facebook.com/profile.php?id=100006625389908" target="_blank"><img src="data:image/svg+xml;base64,
            PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAw
            IDI0IDI0Ij48cGF0aCBkPSJNMTIgMmM1LjUxNCAwIDEwIDQuNDg2IDEwIDEwcy00LjQ4NiAxMC0xMCAxMC0xMC00LjQ4Ni0xMC0xM
           CA0LjQ4Ni0xMCAxMC0xMHptMC0yYy02LjYyNyAwLTEyIDUuMzczLTEyIDEyczUuMzczIDEyIDEyIDEyIDEyLTUuMzczIDEyLTEyLT
           UuMzczLTEyLTEyLTEyem0tMiAxMGgtMnYyaDJ2Nmgzdi02aDEuODJsLjE4LTJoLTJ2LS44MzNjMC0uNDc4LjA5Ni0uNjY3LjU1OC0
           uNjY3aDEuNDQydi0yLjVoLTIuNDA0Yy0xLjc5OCAwLTIuNTk2Ljc5Mi0yLjU5NiAyLjMwOHYxLjY5MnoiLz48L3N2Zz4="></a>
    </div>
    <div class="icon insta">
        <a href="https://www.instagram.com/salmankhansrklover/" target="_blank">
            <img
                src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBkPSJNMT
            IgMmM1LjUxNCAwIDEwIDQuNDg2IDEwIDEwcy00LjQ4NiAxMC0xMCAxMC0xMC00LjQ4Ni0xMC0xMCA0LjQ4Ni0xMCAxMC0xMHptMC0yYy02LjYyNyAwLTEyIDUuMzczLTEyIDEyczUuMzczIDEyIDEyIDEyIDE
            yLTUuMzczIDEyLTEyLTUuMzczLTEyLTEyLTEyem0wIDcuMDgyYzEuNjAyIDAgMS43OTIuMDA2IDIuNDI1LjAzNSAxLjYyNy4wNzQgMi4zODUuODQ1IDIuNDYgMi40NTkuMDI4LjYzMy4wMzQuODIyLjAzNCAy
            LjQyNHMtLjAwNiAxLjc5Mi0uMDM0IDIuNDI0Yy0uMDc1IDEuNjEzLS44MzIgMi4zODYtMi40NiAyLjQ2LS42MzMuMDI4LS44MjIuMDM1LTIuNDI1LjAzNS0xLjYwMiAwLTEuNzkyLS4wMDYtMi40MjQtLjAzN
            S0xLjYzLS4wNzUtMi4zODUtLjg0OS0yLjQ2LTIuNDYtLjAyOC0uNjMyLS4wMzUtLjgyMi0uMDM1LTIuNDI0cy4wMDctMS43OTIuMDM1LTIuNDI0Yy4wNzQtMS42MTUuODMyLTIuMzg2IDIuNDYtMi40Ni42Mz
            ItLjAyOS44MjItLjAzNCAyLjQyNC0uMDM0em0wLTEuMDgyYy0xLjYzIDAtMS44MzMuMDA3LTIuNDc0LjAzNy0yLjE4LjEtMy4zOSAxLjMwOS0zLjQ5IDMuNDg5LS4wMjkuNjQxLS4wMzYuODQ1LS4wMzYgMi4
            0NzQgMCAxLjYzLjAwNyAxLjgzNC4wMzYgMi40NzQuMSAyLjE3OSAxLjMxIDMuMzkgMy40OSAzLjQ5LjY0MS4wMjkuODQ0LjAzNiAyLjQ3NC4wMzYgMS42MyAwIDEuODM0LS4wMDcgMi40NzUtLjAzNiAyLjE3
            Ni0uMSAzLjM5MS0xLjMwOSAzLjQ4OS0zLjQ5LjAyOS0uNjQuMDM2LS44NDQuMDM2LTIuNDc0IDAtMS42MjktLjAwNy0xLjgzMy0uMDM2LTIuNDc0LS4wOTgtMi4xNzctMS4zMDktMy4zOS0zLjQ4OS0zLjQ4O
            S0uNjQxLS4wMy0uODQ1LS4wMzctMi40NzUtLjAzN3ptMCAyLjkxOWMtMS43MDEgMC0zLjA4MSAxLjM3OS0zLjA4MSAzLjA4MXMxLjM4IDMuMDgxIDMuMDgxIDMuMDgxIDMuMDgxLTEuMzc5IDMuMDgxLTMuMD
            gxYzAtMS43MDEtMS4zOC0zLjA4MS0zLjA4MS0zLjA4MXptMCA1LjA4MWMtMS4xMDUgMC0yLS44OTUtMi0yIDAtMS4xMDQuODk1LTIgMi0yIDEuMTA0IDAgMi4wMDEuODk1IDIuMDAxIDJzLS44OTcgMi0yLjA
            wMSAyem0zLjIwMi01LjkyMmMtLjM5NyAwLS43Mi4zMjItLjcyLjcyIDAgLjM5Ny4zMjIuNzIuNzIuNzIuMzk4IDAgLjcyMS0uMzIyLjcyMS0uNzIgMC0uMzk4LS4zMjItLjcyLS43MjEtLjcyeiIvPjwvc3ZnPg==">
        </a>
    </div>
    <div class="icon whatsapp">
        <a href="https://wa.me/19599872936
        " target="_blank">
            <img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBkPSJNMT
            IgMmM1LjUxNCAwIDEwIDQuNDg2IDEwIDEwcy00LjQ4NiAxMC0xMCAxMC0xMC00LjQ4Ni0xMC0xMCA0LjQ4Ni0xMCAxMC0xMHptMC0yYy02LjYyNyAwLTEyIDUuMzczLTEyIDEyczUuMzczIDEyIDEyIDEyIDE
            yLTUuMzczIDEyLTEyLTUuMzczLTEyLTEyLTEyem0tNS45NzEgMThsLjg0NC0zLjA4MWMtLjUyLS45MDItLjc5NC0xLjkyNS0uNzk0LTIuOTczLjAwMS0zLjI3OSAyLjY2OC01Ljk0NiA1Ljk0Ni01Ljk0NiAx
            LjU5MS4wMDEgMy4wODQuNjIgNC4yMDYgMS43NDQgMS4xMjMgMS4xMjQgMS43NDEgMi42MTggMS43NCA0LjIwNy0uMDAxIDMuMjc5LTIuNjY5IDUuOTQ2LTUuOTQ2IDUuOTQ2LS45OTUgMC0xLjk3Ni0uMjUtM
            i44NDQtLjcyNGwtMy4xNTIuODI3em0zLjI5OC0xLjkwM2MuODM4LjQ5NyAxLjYzOC43OTYgMi42OTYuNzk2IDIuNzI0IDAgNC45NDMtMi4yMTcgNC45NDQtNC45NDIuMDAxLTIuNzMxLTIuMjA4LTQuOTQ1LT
            QuOTQtNC45NDYtMi43MjYgMC00Ljk0MyAyLjIxNy00Ljk0NCA0Ljk0MiAwIDEuMTEyLjMyNiAxLjk0Ni44NzMgMi44MTdsLS40OTkgMS44MjQgMS44Ny0uNDkxem01LjY5NC0yLjczMmMtLjAzNy0uMDYyLS4
            xMzYtLjA5OS0uMjg1LS4xNzQtLjE0OS0uMDc0LS44NzktLjQzNC0xLjAxNS0uNDgzLS4xMzYtLjA1LS4yMzUtLjA3NC0uMzM0LjA3NC0uMDk5LjE0OS0uMzg0LjQ4My0uNDcuNTgzLS4wODcuMDk5LS4xNzMu
            MTEyLS4zMjIuMDM3LS4xNDktLjA3NC0uNjI3LS4yMzEtMS4xOTUtLjczNy0uNDQyLS4zOTQtLjc0LS44ODEtLjgyNy0xLjAyOS0uMDg3LS4xNDktLjAwOS0uMjI5LjA2NS0uMzAzbC4yMjMtLjI2LjE0OS0uM
            jQ4Yy4wNS0uMDk5LjAyNS0uMTg2LS4wMTItLjI2bC0uNDU4LTEuMTAzYy0uMTIxLS4yOS0uMjQzLS4yNS0uMzM0LS4yNTVsLS4yODYtLjAwN2MtLjA5OSAwLS4yNi4wMzctLjM5Ni4xODZzLS41Mi41MDgtLj
            UyIDEuMjRjMCAuNzMxLjUzMiAxLjQzOC42MDcgMS41MzcuMDc0LjA5OSAxLjA0OCAxLjYgMi41MzggMi4yNDMuMzU0LjE1My42MzEuMjQ1Ljg0Ny4zMTMuMzU2LjExMy42OC4wOTcuOTM2LjA1OS4yODUtLjA
            0My44NzktLjM1OSAxLjAwMy0uNzA2LjEyMy0uMzQ4LjEyMy0uNjQ1LjA4Ni0uNzA3eiIvPjwvc3ZnPg==">
        </a>
    </div>
    <div class="icon telegram"> 
        <a href="http://www.telegram.com" target="_blank"> <img
                src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLj
                EvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj48c3ZnIHdpZHRoPSIyNHB4IiBoZWlnaHQ9IjI0cHgiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly9
                3d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSIgeG1sbnM6c2VyaWY9Imh0dHA6Ly93d3cuc2VyaWYuY29t
                LyIgc3R5bGU9ImZpbGwtcnVsZTpldmVub2RkO2NsaXAtcnVsZTpldmVub2RkO3N0cm9rZS1saW5lam9pbjpyb3VuZDtzdHJva2UtbWl0ZXJsaW1pdDoxLjQxNDIxOyI+PHBhdGggaWQ9InRlbGVncmFtLTUiI
                GQ9Ik0xMiwwYy02LjYyNywwIC0xMiw1LjM3MyAtMTIsMTJjMCw2LjYyNyA1LjM3MywxMiAxMiwxMmM2LjYyNywwIDEyLC01LjM3MyAxMiwtMTJjMCwtNi42MjcgLTUuMzczLC0xMiAtMTIsLTEyWm0wLDJjNS
                41MTQsMCAxMCw0LjQ4NiAxMCwxMGMwLDUuNTE0IC00LjQ4NiwxMCAtMTAsMTBjLTUuNTE0LDAgLTEwLC00LjQ4NiAtMTAsLTEwYzAsLTUuNTE0IDQuNDg2LC0xMCAxMCwtMTBabTIuNjkyLDE0Ljg4OWMwLjE
                2MSwwLjExNSAwLjM2OCwwLjE0MyAwLjU1MywwLjA3M2MwLjE4NSwtMC4wNyAwLjMyMiwtMC4yMjggMC4zNjIsLTAuNDJjMC40MzUsLTIuMDQyIDEuNDg5LC03LjIxMSAxLjg4NCwtOS4wNjhjMC4wMywtMC4x
                NCAtMC4wMTksLTAuMjg1IC0wLjEyOSwtMC4zNzljLTAuMTEsLTAuMDkzIC0wLjI2MywtMC4xMiAtMC4zOTksLTAuMDdjLTIuMDk2LDAuNzc2IC04LjU1MywzLjE5OCAtMTEuMTkyLDQuMTc1Yy0wLjE2OCwwL
                jA2MiAtMC4yNzcsMC4yMjMgLTAuMjcxLDAuNGMwLjAwNiwwLjE3NyAwLjEyNSwwLjMzIDAuMjk2LDAuMzgxYzEuMTg0LDAuMzU0IDIuNzM4LDAuODQ3IDIuNzM4LDAuODQ3YzAsMCAwLjcyNSwyLjE5MyAxLj
                EwNCwzLjMwOGMwLjA0NywwLjEzOSAwLjE1NywwLjI1IDAuMzAxLDAuMjg3YzAuMTQ1LDAuMDM4IDAuMjk4LC0wLjAwMSAwLjQwNiwtMC4xMDNjMC42MDgsLTAuNTc0IDEuNTQ4LC0xLjQ2MSAxLjU0OCwtMS4
                0NjFjMCwwIDEuNzg2LDEuMzA5IDIuNzk5LDIuMDNabS01LjUwNSwtNC4zMzhsMC44NCwyLjc2OWwwLjE4NiwtMS43NTRjMCwwIDMuMjQzLC0yLjkyNSA1LjA5MiwtNC41OTNjMC4wNTUsLTAuMDQ4IDAuMDYy
                LC0wLjEzIDAuMDE3LC0wLjE4OGMtMC4wNDUsLTAuMDU3IC0wLjEyNiwtMC4wNzEgLTAuMTg4LC0wLjAzMmMtMi4xNDMsMS4zNjggLTUuOTQ3LDMuNzk4IC01Ljk0NywzLjc5OFoiLz48L3N2Zz4=">
        </a>
    </div>

</div>
{% endblock %}
{% block js %}
<script>
console.log("Reached")
{%if thank %}
alert('Thanks for contacting Us. We will Get back to you so soon!');
document.location="/shop/contactus";
{% endif %}
</script>
{% endblock %}

blog/templates/blog/index.html
{%extends 'blog/basic.html'%}
{%block css%}{%endblock%}
{%block body%}

<div class="newpost "></div>

<a href="/blog/createpost" rel="noopener noreferrer" type="button">Click</a>

<div class="container mt-3">
    <div class="row my-2">
        {% for item in myposts %}
        <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary">
                        {{item.title}}
                    </strong>
                    <h3 class="mb-0">{{item.tilte}}</h3>
                    <div class="mb-1 text-muted"></div>
                    <p class="card-text mb-auto">{{item.head1}}</p>
                    <a href="blogpost/{{item.post_id}}" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <img src="/media/{{item.thumbnail}}" class="bd-placeholder-img" width="200" height="250" aria-label="Placeholder: Thumbnail">
                    <title>Placeholder</title></img>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:2%}
    </div>
    <div class="row my-2">
        {%endif%}
        {%endfor%}</div>
</div>
{%endblock%}